CREATE TABLE INFUSE.CLIENTE (
	ID_CLIENTE BIGINT AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
)

CREATE TABLE INFUSE.PEDIDO (
	ID_PEDIDO BIGINT AUTO_INCREMENT NOT NULL,
	NUMERO_CONTROLE BIGINT NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	NOME_PRODUTO VARCHAR(255) NOT NULL,
	VALOR_PRODUTO DECIMAL(15,2) NOT NULL,
	QUANTIDADE_PRODUTO INT NOT NULL,
	CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO)
)

CREATE TABLE INFUSE.PEDIDO_CLIENTE (
	ID_PEDIDO_CLIENTE BIGINT AUTO_INCREMENT NOT NULL,
	ID_CLIENTE BIGINT NOT NULL,
	ID_PEDIDO BIGINT NOT NULL,
	VALOR_PEDIDO DECIMAL(15,2) NOT null,
	CONSTRAINT PK_PEDIDO_CLIENTE PRIMARY KEY (ID_PEDIDO_CLIENTE),
	CONSTRAINT FK_PEDIDO_CLIENTE_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
	CONSTRAINT FK_PEDIDO_CLIENTE_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
)

ALTER TABLE INFUSE.CLIENTE ADD CONSTRAINT UC_CLIENTE UNIQUE (ID_CLIENTE, CPF_CNPJ)
ALTER TABLE INFUSE.PEDIDO ADD CONSTRAINT UC_PEDIDO UNIQUE (ID_PEDIDO, NUMERO_CONTROLE)
ALTER TABLE INFUSE.PEDIDO_CLIENTE ADD COLUMN DESCONTO BOOLEAN

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(1, 'Leandro Augusto', '12345678985');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(2, 'Junior Silva', '25698798965');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(3, 'Mateus Neves', '03698745214');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(4, 'Ricardo Santos', '98758965414');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(5, 'Maria Silva', '85296314755');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(6, 'João Lima', '47125896522');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(7, 'Juliana Amaral', '01236544789');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(8, 'Roberto Souza', '22658974456');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(9, 'Luana Mendes', '22365454889');

INSERT INTO infuse.cliente
(ID_CLIENTE, NOME, CPF_CNPJ)
VALUES(10, 'Jose Silva', '85698745235');