spring:
  application:
    name: api-customer-request
  datasource:
    url: ${url-db:jdbc:mysql://localhost:3306/infuse}
    username: ${user-db:admin}
    password: ${password-db:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
    
server:
  port: 8080
  error:
    include-message: always
  